version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - /Users/navi/Documents/diplomski-rad/autodb-backend/docker/data/master:/var/opt/mssql/backup
    restart: unless-stopped

volumes:
  mssql-data:
