version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - autodb-network
    command: redis-server --appendonly yes

networks:
  autodb-network:
    driver: bridge

volumes:
  redis-data:
